version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      siderolabs:
        patterns:
          - "github.com/siderolabs/*"
      kubernetes:
        patterns:
          - "k8s.io/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
